## Hard-core sampling w Gibbs sampler

Here is a implementation of Gibbs sampler algorithm for the hard-core problem.

In [1]:
import random
import numpy as np
import pandas as pd

### Create grid for particles

In [2]:
# Set K value for grid size (kxk) suggested 3<=K<=20
K = 5

# Create a kxk matrix initialized with no particles (you can actually initialize in whichever way you would like lol)
grid = np.zeros((K, K), dtype=int)

print(f"Created {K}x{K} grid:")
print(grid)

Created 5x5 grid:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Gibbs random sampler

In [ ]:
def run_gibbs_random(grid):
    """Move from X_{n} state to X_{n+1} using Gibbs random sampler."""
    # First we select a random vertex on our grid
    i = random.randint(0, K-1)
    j = random.randint(0, K-1)

    # Sample another value for vertex given the other vertex
    # Check if neighbor vertex are 0 (for possible particle in factible grid)
    # Boundary cases
    neighbors_empty = True  # Start assuming neighbors are empty
    
    # Check top neighbor (only if not at top boundary)
    if i > 0 and grid[i-1, j] == 1:
        neighbors_empty = False
    
    # Check bottom neighbor (only if not at bottom boundary)
    if i < K-1 and grid[i+1, j] == 1:
        neighbors_empty = False
    
    # Check left neighbor (only if not at left boundary)
    if j > 0 and grid[i, j-1] == 1:
        neighbors_empty = False
    
    # Check right neighbor (only if not at right boundary)
    if j < K-1 and grid[i, j+1] == 1:
        neighbors_empty = False
    
    if neighbors_empty:
        coin_flipped = random.randint(0,1) # One for heads, zero for tails 
        if coin_flipped == 1:
            grid[i, j] = 1 # Put particle
        else:
            grid[i,j] = 0 # Remove particle
    else:
        grid[i,j] == 0 # If neighbors have particles force no particle in vertex

    return grid
    

### Gibbs sampler w order

### Run Gibbs sampler